@startuml

title __MAIN's Class Diagram__\n

  namespace main {
    class main.Client {
        - anschrift : String
        - name : String
        - postleitzahl : int
        - stadt : String
        - vorname : String
        + Client()
        + getAnschrift()
        + getName()
        + getPostleitzahl()
        + getStadt()
        + getVorname()
        + setAnschrift()
        + setName()
        + setPostleitzahl()
        + setStadt()
        + setVorname()
    }
  }


  namespace main {
    class main.ClientControl {
        {static} + loadClientsFromDB()
        {static} + startClientControl()
        {static} - writeClient()
        {static} - SaveClientInDB()
        {static} - selectOption()
        {static} - loadClient()
    }
  }
  

  namespace main {
    class main.Main {
        {static} + main()
    }
  }
  

  namespace main {
    class main.PDFPrinter {
        {static} + generatePDF()
    }
  }
  

  namespace main {
    abstract class main.TransportMean {
        + idTransportMean : int
    }
  }
  

  namespace main {
    class main.Validation {
        {static} + testAddress()
        {static} + testPostalCode()
        {static} + testSentence()
        {static} + testXMLPAth()
        {static} - testDigitString()
        {static} - testLength5()
        {static} - testNullString()
        {static} - testOnlyDigits()
        {static} - testSpecialCharsString()
    }
  }
  

  namespace main {
    class main.Vehicle {
        - bezeichnung : String
        - fahrzeugtyp : String
        - heersteller : String
        - kw_leistung : int
        - verkaufspreis : int
        + getBezeichnung()
        + getFahrzeugtyp()
        + getHeersteller()
        + getKw_leistung()
        + getVerkaufspreis()
        + setBezeichnung()
        + setFahrzeugtyp()
        + setHeersteller()
        + setIdTransportMean()
        + setKw_leistung()
        + setVerkaufspreis()
    }
  }
  

  namespace main {
    class main.VehicleControl {
        {static} + loadVehiclesFromDB()
        + saveVehiclesinDB()
        - getTagValue()
        - getVehicle()
        {static} - loadVehicle()
        - readXML()
    }
  }
  

  main.Vehicle -up-|> main.TransportMean

  main.Main--main.ClientControl
  main.Main--main.VehicleControl
  main.Main--main.PDFPrinter
  main.VehicleControl--main.Vehicle
  main.ClientControl--main.Client
  main.VehicleControl--main.Validation
  main.ClientControl--main.Validation


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
